name: avr-framework-ci
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
jobs:
  set-unknown-state-badges-for-CI:
    runs-on: ubuntu-latest
    steps:
      - name: "Create badge BuildDockerImage with unknown state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeBuildDockerImage.json
          label: Build
          message: unknown
          color: grey
      - name: "Create badge UTX8664Cmake with unknown state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664Cmake.json
          label: CMake
          message: unknown
          color: grey
      - name: "Create badge UTX8664Build with unknown state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664Build.json
          label: Make-Build
          message: unknown
          color: grey
      - name: "Create badge UTX8664CTest with unknown state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664CTest.json
          label: CTest
          message: unknown
          color: grey
  start-azure-runner:
    runs-on: ubuntu-latest
    needs: set-unknown-state-badges-for-CI
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Start GitHub self-hosted runner
        run: |
          az vm start -g github-ci-resource-group -n github-ci-runner
  build-avr-framework-docker-image:
    runs-on: [self-hosted, Azure, Docker]
    needs: start-azure-runner
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: "Build image from Dockerfile"
        run: docker --log-level=debug build . --file=docker/Dockerfile --tag my-user/avr-framework:latest
      - name: "Create badge BuildDockerImage with passing state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeBuildDockerImage.json
          label: Build
          message: passing
          color: green
      - name: "Create badge BuildDockerImage with failing state"
        if: ${{ failure() }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeBuildDockerImage.json
          label: Build
          message: failing
          color: red
  run-UT-in-avr-framework-container:
    runs-on: [self-hosted, Azure, Docker]
    needs: build-avr-framework-docker-image
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Set executable privileges to CI run scripts
        run: |
          chmod +x ${{ github.workspace }}/ci/ut/runCMake.sh
          chmod +x ${{ github.workspace }}/ci/ut/runCTest.sh
          chmod +x ${{ github.workspace }}/ci/ut/runMake.sh
      - name: "Check docker container availability"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            echo "Executed in docker container. Test: OK!"
      - name: "Create directory for build artifacts"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT
            mkdir -p buildCI
      - name: "Run CMake for UT"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT/buildCI
            bash ../ci/ut/runCMake.sh
      - name: "Create badge UTX8664Cmake with passing state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664Cmake.json
          label: CMake
          message: passing
          color: green
      - name: "Create badge UTX8664Cmake with passing state"
        if: ${{ failure() }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664Cmake.json
          label: CMake
          message: failing
          color: red
      - name: "Run Make for UT"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT/buildCI
            bash ../ci/ut/runMake.sh
      - name: "Create badge UTX8664Build with passing state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664Build.json
          label: Make-Build
          message: passing
          color: green
      - name: "Create badge UTX8664Build with passing state"
        if: ${{ failure() }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664Build.json
          label: Make-Build
          message: failing
          color: red
      - name: "Run CTest for UT"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT/buildCI
            bash ../ci/ut/runCTest.sh
      - name: "Create badge UTX8664CTest with passing state"
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664CTest.json
          label: CTest
          message: passing
          color: green
      - name: "Create badge UTX8664CTest with passing state"
        if: ${{ failure() }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_CI_TOKEN }}
          gistID: 536fc4300ff360bc55fbf7d1b618ef4c
          filename: badgeUTX8664CTest.json
          label: CTest
          message: failing
          color: red
      - name: "Cleanup build artifacts"
        if: ${{ always() }}
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT
            rm -r -f buildCI
  stop-azure-runner:
    runs-on: ubuntu-latest
    needs: [build-avr-framework-docker-image, run-UT-in-avr-framework-container]
    if: ${{ always() }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Stop GitHub self-hosted runner
        run: |
          az vm deallocate -g github-ci-resource-group -n github-ci-runner --no-wait
