name: AVR-Framework-CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  start-azure-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Start GitHub self-hosted runner
        run: |
          az vm start -g github-ci-resource-group -n github-ci-runner
  checkout-repo:
    runs-on: [self-hosted, Azure, Docker]
    needs: start-azure-runner
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
  build-avr-build-env-image:
    runs-on: [self-hosted, Azure, Docker]
    needs: checkout-repo
    working-directory: docker
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Build image from Dockerfile"
        uses: docker/build-push-action@main
        with:
          context: .
          file: Dockerfile
          push: false
          tags: bkozdras/avr-build-env:latest
  run-UT-in-avr-build-env:
    runs-on: [self-hosted, Azure, Docker]
    needs: build-avr-build-env-image
    steps:
      - name: "Run example command in avr-build-env"
        uses: addnab/docker-run-action@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: bkozdras/avr-build-env:latest
          shell: bash
          options: -v ${{ github.workspace }}:/workspace
          run: |
            ./buildUT.sh
  stop-azure-runner:
    runs-on: ubuntu-latest
    needs: run-UT-in-avr-build-env
    steps:
      - name: Login to Azure
        if: ${{ always() }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Stop GitHub self-hosted runner
        if: ${{ always() }}
        run: |
          az vm deallocate -g github-ci-resource-group -n github-ci-runner --no-wait
  
