name: AVR-Framework-CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  start-azure-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Start GitHub self-hosted runner
        run: |
          az vm start -g github-ci-resource-group -n github-ci-runner
  build-avr-framework-docker-image:
    runs-on: [self-hosted, Azure, Docker]
    needs: start-azure-runner
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: "Build image from Dockerfile"
        run: docker --log-level=debug build . --file=docker/Dockerfile --tag my-user/avr-framework:latest
  run-UT-in-avr-framework-container:
    runs-on: [self-hosted, Azure, Docker]
    needs: build-avr-framework-docker-image
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Set executable privileges to ${{ github.workspace }}/buildUT.sh
        run: |
          chmod +x ${{ github.workspace }}/buildUT.sh
      - name: "Run example command in avr-build-env"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd workspace
            ls -la
            THIS_ARCH=$(uname -m | tr -d '\n')
            mkdir -p build_$THIS_ARCH
            cd build_$THIS_ARCH
            cmake \
              -DAVR_FRAMEWORK_BUILD_LIBRARY_STATIC=ON \
              -DAVR_FRAMEWORK_BUILD_STUB_LIBRARY_STATIC=ON
              -DAVR_FRAMEWORK_UNIT_TESTING_ENABLED=ON ..
            chmod +x ../buildUT.sh
  stop-azure-runner:
    runs-on: ubuntu-latest
    needs: [build-avr-framework-docker-image, run-UT-in-avr-framework-container]
    if: ${{ always() }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Stop GitHub self-hosted runner
        run: |
          az vm deallocate -g github-ci-resource-group -n github-ci-runner --no-wait
  
