name: AVR-Framework-CI

on: [push]

jobs:
  start-azure-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Start GitHub self-hosted runner
        run: |
          az vm start -g github-ci-resource-group -n github-ci-runner
  build-avr-framework-docker-image:
    runs-on: [self-hosted, Azure, Docker]
    needs: start-azure-runner
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: "Build image from Dockerfile"
        run: docker --log-level=debug build . --file=docker/Dockerfile --tag my-user/avr-framework:latest
  run-UT-in-avr-framework-container:
    runs-on: [self-hosted, Azure, Docker]
    needs: build-avr-framework-docker-image
    steps:
      - name: Checkout / clone GitHub repo
        uses: actions/checkout@main
        with:
          submodules: true
      - name: Set executable privileges to CI run scripts
        run: |
          chmod +x ${{ github.workspace }}/ci/ut/runCMake.sh
          chmod +x ${{ github.workspace }}/ci/ut/runCTest.sh
          chmod +x ${{ github.workspace }}/ci/ut/runMake.sh
      - name: "Create file with build"
        run: |
          mkdir -p buildCI
      - name: "Check docker container availability"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            echo "Executed in docker container. Test: OK!"
      - name: "Run CMake for UT"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT/buildCI
            bash ../ci/ut/runCMake.sh
      - name: "Run Make for UT"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT/buildCI
            bash ../ci/ut/runMake.sh
      - name: "Run CTest for UT"
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          image: my-user/avr-framework:latest
          options: -v ${{ github.workspace }}:/workspaceUT
          run: |
            cd workspaceUT/buildCI
            bash ../ci/ut/runCTest.sh
  stop-azure-runner:
    runs-on: ubuntu-latest
    needs: [build-avr-framework-docker-image, run-UT-in-avr-framework-container]
    if: ${{ always() }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Stop GitHub self-hosted runner
        run: |
          az vm deallocate -g github-ci-resource-group -n github-ci-runner --no-wait
