name: AVR-Framework-CI

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  start-azure-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Start self-hosted runner
        run: |
            az vm start -g github-ci-resource-group -n github-ci-runner
  stop-azure-runner:
    runs-on: ubuntu-18.04
    needs: start-azure-runner
    steps:
      - name: Login 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deallocate self-hosted runner
        run: |
          az vm deallocate -g ci-rg -n ci-runner --no-wait
  
